# AWS configuration example
deployment_mode: aws
aws_region: us-east-1
secrets:
  api_key_secret_name: git-deploy-healer/API_KEY
  github_webhook_secret_name: git-deploy-healer/GITHUB_WEBHOOK_SECRET

# AWS SSM parameter names
database:
  url: /pypaas/DATABASE_URL

api:
  key: /pypaas/API_KEY
  github_webhook_secret: /pypaas/GITHUB_WEBHOOK_SECRET

docker_registry:
  url: /pypaas/DOCKER_REGISTRY_URL
  username: /pypaas/DOCKER_REGISTRY_USERNAME
  password: /pypaas/DOCKER_REGISTRY_PASSWORD
