# Local configuration used during development
deployment_mode: local
database:
  url: ${DATABASE_URL}
secrets:
  github_webhook_secret: ${GITHUB_WEBHOOK_SECRET}

api:
  key: ${API_KEY}

docker_registry:
  url: ${DOCKER_REGISTRY_URL}
  username: ${DOCKER_REGISTRY_USERNAME}
  password: ${DOCKER_REGISTRY_PASSWORD}
